### ISSUE TITLE
A question for ya buddy

### ISSUE THREAD

**Issue by ThatOneBepis** [Garmundo/Extended-unit-arsenal#10]
Would you mind if i take some js from turrets/units and use it in my own way?

**Comment by Garmundo** [comment]
Uhm I don't have scripts tho, you might want to look at AdvancedContent for those. If you're looking to use json files or make things that closely resemble my stuff conceptually you can, maybe you can give me some credit hehe

Thx for asking before doing btw

**Comment by ThatOneBepis** [comment]
Indeed, we should take care of eachother
