### ISSUE TITLE
Alternative to infinitodustry

### ISSUE THREAD

**Issue by daniel071** [Garmundo/Extended-unit-arsenal#2]
In your `README.md` file, you stated

> "(if you want to play around with the units in sandbox I recommend downloading infinitodustry and using the overjector because capital ship production time is SLOW)"

You can also click on on Customise Rules and change the Unit Production Speed Multiplier to something higher than 1

![image](https://user-images.githubusercontent.com/45705145/78768980-073fc680-79d0-11ea-903a-b0c88e7426e3.png)

![image](https://user-images.githubusercontent.com/45705145/78768807-cb0c6600-79cf-11ea-9600-15708fa5a497.png)

Maybe you should add this to the `README.md`

**Comment by Garmundo** [comment]
Great idea! I didn't realize this. I added it in the README
